name: CPack

on:
 push:
  branches: [gad]
 pull_request:
  branches: [gad]

jobs: 
 build_Linux:

  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v4

  - name: Configure solver
    run: cmake ${{github.workspace}} -B ${{github.workspace}}/build

  - name: Build solver
    run: cmake --build ${{github.workspace}}/build
